import {Visuals,presets} from './visuals.mjs';
const $=id=>document.getElementById(id),bridge=window.desktop;
const defaults={preset:0,mode:1,gain:1.5,duration:90,quality:1.5,shuffle:false,showClock:false,showTrack:true,enabled:presets.map(p=>p.id)};
let saved;try{saved=JSON.parse(localStorage.getItem('preferences')||'{}');}catch{saved={};}
const state={...defaults,...saved};state.preset=Math.max(0,Math.min(presets.length-1,Number(state.preset)||0));state.enabled=Array.isArray(state.enabled)?state.enabled.filter(i=>presets[i]):defaults.enabled;
const visuals=new Visuals($('visual'));const player=$('player');let sourceList,frame={bins:new Array(96).fill(0),rms:0},demo=false,playlist=[],track=0,lastShuffle=0,audioContext,analyser,fileSource,playingFile=false,fps=0,frames=0,fpsAt=performance.now();
function persist(){localStorage.setItem('preferences',JSON.stringify(state));}
function message(s){$('status').textContent=s;}
function setPreset(id){state.preset=id;visuals.setPreset(id);$('presetTitle').textContent=presets[id].name;document.querySelectorAll('article').forEach(a=>a.classList.toggle('selected',Number(a.dataset.id)===id));persist();}
function setMode(mode){state.mode=mode;visuals.mode=mode;document.body.classList.toggle('lightMode',mode>=2);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',Number(b.dataset.mode)===mode));persist();}
const demoFrame=t=>({bins:Array.from({length:96},(_,i)=>Math.max(0,Math.sin(i*.2+t*1.4)*.16+.12+Math.exp(-Math.pow((i-18-12*Math.sin(t*.8))/9,2))*(.35+.25*Math.sin(t*3)))),rms:.13+.06*Math.sin(t*3)});
function buildGallery(){const chosen=state.preset,mode=state.mode;visuals.mode=1;const f=demoFrame(2);for(const p of presets){visuals.setPreset(p.id);for(let i=0;i<4;i++)visuals.render(2+i*.03,f.bins,f.rms);const article=document.createElement('article');article.dataset.id=p.id;const b=document.createElement('button');b.className='selectPreset';b.title=p.name;b.setAttribute('aria-label','Select '+p.name);const image=new Image();image.src=visuals.thumbnail();image.alt='';const name=document.createElement('span');name.className='name';name.textContent=p.name;b.append(image,name);b.onclick=()=>{setPreset(p.id);$('gallery').hidden=true;};const check=document.createElement('button');check.className='include';check.textContent='✓';check.title='Include '+p.name+' in shuffle';check.setAttribute('aria-label',check.title);check.classList.toggle('enabled',state.enabled.includes(p.id));check.setAttribute('aria-pressed',state.enabled.includes(p.id));check.onclick=()=>{if(state.enabled.includes(p.id))state.enabled=state.enabled.filter(i=>i!==p.id);else state.enabled.push(p.id);check.classList.toggle('enabled',state.enabled.includes(p.id));check.setAttribute('aria-pressed',state.enabled.includes(p.id));persist();};article.append(b,check);$('cards').append(article);}setMode(mode);setPreset(chosen);}
function panel(id){const open=$(id).hidden;$('gallery').hidden=true;$('settings').hidden=true;$(id).hidden=!open;document.body.classList.remove('hiddenControls');}
async function refresh(){try{const previous=$('source').value;sourceList=await bridge.sources();$('source').replaceChildren(...sourceList.sources.map(s=>{const o=document.createElement('option');o.value=s.name;o.textContent=(s.monitor?'System · ':'Mic · ')+s.label;return o;}));if(sourceList.sources.some(s=>s.name===previous))$('source').value=previous;}catch(e){message('Cannot access audio: '+e.message);}}
async function capture(name){try{await bridge.capture(name);player.pause();playingFile=false;demo=false;$('demo').classList.remove('active');$('source').value=name;for(const id of ['system','microphone'])$(id).classList.toggle('active',id===(sourceList.sources.find(s=>s.name===name)?.monitor?'system':'microphone'));message('Listening · '+(sourceList.sources.find(s=>s.name===name)?.label||name));}catch(e){message(e.message);}}
async function useSystem(){await refresh();if(sourceList)await capture(sourceList.defaultMonitor);}
function ensureAnalyser(){if(!audioContext){audioContext=new AudioContext();analyser=audioContext.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.7;fileSource=audioContext.createMediaElementSource(player);fileSource.connect(analyser);analyser.connect(audioContext.destination);}return audioContext.resume();}
async function playTrack(index){if(!playlist.length){message('Choose music files first.');return;}track=(index+playlist.length)%playlist.length;await bridge.stop();frame={bins:new Array(96).fill(0),rms:0};demo=false;playingFile=true;await ensureAnalyser();player.src=playlist[track].url;try{await player.play();message('Playing local music');$('trackInfo').textContent=state.showTrack?playlist[track].name:'';$('system').classList.remove('active');$('microphone').classList.remove('active');$('demo').classList.remove('active');}catch(e){message('Cannot play '+playlist[track].name+': '+e.message);}}
$('music').onclick=async()=>{const files=await bridge.music();if(files.length){playlist=files;await playTrack(0);}};
$('system').onclick=useSystem;$('microphone').onclick=async()=>{await refresh();const mic=sourceList?.sources.find(s=>!s.monitor);if(mic)await capture(mic.name);else message('No microphone found.');};
$('source').onchange=()=>capture($('source').value);$('refresh').onclick=refresh;
$('play').onclick=async()=>{if(!playlist.length){$('music').click();return;}if(player.paused){await ensureAnalyser();try{await player.play();}catch(e){message(e.message);}}else player.pause();};
player.onplay=()=>{$('play').textContent='Ⅱ';};player.onpause=()=>{$('play').textContent='▶';};player.onended=()=>playTrack(track+1);player.onerror=()=>message('This audio file could not be decoded. Try WAV, FLAC, OGG or MP3.');
$('previous').onclick=()=>playTrack(track-1);$('next').onclick=()=>playTrack(track+1);
$('galleryButton').onclick=()=>panel('gallery');$('settingsButton').onclick=()=>panel('settings');$('closeGallery').onclick=()=>{$('gallery').hidden=true;};$('closeSettings').onclick=()=>{$('settings').hidden=true;};
$('search').oninput=()=>document.querySelectorAll('article').forEach(a=>{a.hidden=!presets[Number(a.dataset.id)].name.toLowerCase().includes($('search').value.toLowerCase());});
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>setMode(Number(b.dataset.mode));
for(const key of ['gain','duration','quality','shuffle','showClock','showTrack']){const el=$(key);if(el.type==='checkbox')el.checked=!!state[key];else el.value=state[key];el.oninput=()=>{state[key]=el.type==='checkbox'?el.checked:Number(el.value);if(key==='quality'){visuals.renderer.setPixelRatio(Math.min(devicePixelRatio,state.quality));visuals.resize();}if(key==='showTrack')$('trackInfo').textContent=state.showTrack&&playlist[track]?playlist[track].name:'';lastShuffle=performance.now()/1000;persist();};}
$('demo').onclick=async()=>{demo=!demo;$('demo').classList.toggle('active',demo);if(demo){player.pause();playingFile=false;await bridge.stop();$('system').classList.remove('active');$('microphone').classList.remove('active');message('Demo · generated motion, no audio input');}else await useSystem();};
$('fullscreen').onclick=()=>bridge.fullscreen();$('hide').onclick=()=>{document.body.classList.toggle('hiddenControls');$('gallery').hidden=true;$('settings').hidden=true;};
$('diagnostics').onclick=async()=>{const info=visuals.diagnostics(),host=await bridge.diagnostics();$('gpu').textContent=info.renderer+' · '+fps+' FPS · WebGL '+host.features.webgl;};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;if(e.key==='f'||e.key==='F')bridge.fullscreen();if(e.key==='v'||e.key==='V')panel('gallery');if(e.key==='h'||e.key==='H')$('hide').click();if(e.key==='Escape'){$('gallery').hidden=true;$('settings').hidden=true;document.body.classList.remove('hiddenControls');}if(e.key==='ArrowRight')setPreset((state.preset+1)%presets.length);if(e.key==='ArrowLeft')setPreset((state.preset+presets.length-1)%presets.length);if(e.code==='Space'){e.preventDefault();$('play').click();}});
window.addEventListener('resize',()=>visuals.resize());bridge.onFrame(f=>{frame=f;});bridge.onStatus(message);
function animate(ms){requestAnimationFrame(animate);if(document.hidden)return;const t=ms/1000;let current=frame;if(demo)current=demoFrame(t);else if(playingFile&&analyser){const data=new Uint8Array(analyser.frequencyBinCount),wave=new Float32Array(analyser.fftSize);analyser.getByteFrequencyData(data);analyser.getFloatTimeDomainData(wave);current={bins:Array.from({length:96},(_,i)=>{const lo=Math.max(1,Math.floor(30*Math.pow(600,i/96)*analyser.fftSize/audioContext.sampleRate)),hi=Math.min(data.length,Math.max(lo+1,Math.ceil(30*Math.pow(600,(i+1)/96)*analyser.fftSize/audioContext.sampleRate)));let v=0;for(let j=lo;j<hi;j++)v=Math.max(v,data[j]);return v/255;}),rms:Math.sqrt(wave.reduce((sum,v)=>sum+v*v,0)/wave.length)};}
const bins=current.bins.map(x=>Math.min(1,x*state.gain));visuals.render(t,bins,Math.min(1,current.rms*state.gain*3));$('meter').style.height=Math.min(100,current.rms*state.gain*300)+'%';$('clock').textContent=state.showClock?new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';if(state.shuffle&&t-lastShuffle>state.duration){const available=state.enabled.filter(i=>i!==state.preset);if(available.length)setPreset(available[Math.floor(Math.random()*available.length)]);lastShuffle=t;}frames++;if(ms-fpsAt>=1000){fps=Math.round(frames*1000/(ms-fpsAt));frames=0;fpsAt=ms;}}
window.verifyPlayback=async url=>{playlist=[{name:'Verification tone.wav',url}];await playTrack(0);await new Promise(r=>setTimeout(r,450));const data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(data);const peak=Math.max(...data);const result={passed:!player.paused&&player.currentTime>0&&peak>0,currentTime:player.currentTime,frequencyPeak:peak};player.pause();return result;};
window.verifyAll=async()=>{const original={preset:state.preset,mode:state.mode};const results=[];for(let mode=0;mode<4;mode++){visuals.mode=mode;for(const p of presets){visuals.setPreset(p.id);const f=demoFrame(3);visuals.render(3,f.bins,f.rms);const d=visuals.diagnostics();results.push({preset:p.name,mode,webglError:d.webglError,drawCalls:d.drawCalls});}}visuals.mode=original.mode;setPreset(original.preset);const f=demoFrame(4);for(let i=0;i<12;i++)visuals.render(4,f.bins,f.rms);return {passed:results.every(r=>r.webglError===0&&r.drawCalls>0),presets:presets.length,combinations:results.length,renderer:visuals.diagnostics().renderer,results};};
buildGallery();visuals.renderer.setPixelRatio(Math.min(devicePixelRatio,state.quality));visuals.resize();await useSystem();requestAnimationFrame(animate);
