import * as THREE from '../node_modules/three/build/three.module.js';
import {EffectComposer} from '../node_modules/three/examples/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from '../node_modules/three/examples/jsm/postprocessing/RenderPass.js';
import {UnrealBloomPass} from '../node_modules/three/examples/jsm/postprocessing/UnrealBloomPass.js';
export const presets=[
 ['Radial spectrum','radial'],['Wave terrain','terrain'],['Star tunnel','stars'],['Pulse rings','rings'],['Wire globe','globe'],['Constellation','network'],['Spectrum waterfall','waterfall'],['Warp tunnel','tunnel'],['Orbital paths','orbits'],['Prism bloom','prisms'],['Sine ribbons','ribbons'],['Dancing bars','bars'],['Contour ocean','contours'],['Particle sphere','sphere'],['Cube lattice','cubes'],['Nine halos','halos'],['Spiral vortex','vortex'],['Crystal cluster','crystals'],['Oscilloscope','wave'],['Hexagon field','hex'],['Liquid loops','liquid'],['Satellite rings','satellite'],['Pixel rain','pixels'],['Frequency flower','flower']
].map(([name,kind],id)=>({id,name,kind}));
const TAU=Math.PI*2;
export class Visuals {
 constructor(canvas){this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.camera=new THREE.PerspectiveCamera(52,1,.1,100);this.camera.position.set(0,0,13);this.scene=new THREE.Scene();this.group=new THREE.Group();this.scene.add(this.group);this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(1280,850),.8,.5,.25);this.composer.addPass(this.bloom);this.bins=new Float32Array(96);this.level=0;this.mode=1;this.quality=1;this.setPreset(0);this.resize();}
 resize(){const c=this.renderer.domElement;this.renderer.setSize(c.clientWidth,c.clientHeight,false);this.camera.aspect=c.clientWidth/c.clientHeight;this.camera.updateProjectionMatrix();this.composer.setPixelRatio(this.renderer.getPixelRatio());this.composer.setSize(c.clientWidth,c.clientHeight);}
 dispose(){for(const o of [...this.group.children]){this.group.remove(o);o.geometry?.dispose();o.material?.dispose();}this.updateFn=null;}
 lines(count,points=false){const g=new THREE.BufferGeometry();const p=new Float32Array(count*3),c=new Float32Array(count*3);g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(c,3));const m=points?new THREE.PointsMaterial({size:.045,vertexColors:true,transparent:true,opacity:.9,sizeAttenuation:true,blending:THREE.AdditiveBlending}):new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.8});const obj=points?new THREE.Points(g,m):new THREE.LineSegments(g,m);this.group.add(obj);return {p,c,obj,g};}
 color(c,i,h,brightness=1){const col=new THREE.Color();if(this.mode%2===0)col.setRGB(brightness,brightness,brightness);else col.setHSL((h+.54)%1,.9,.56);if(this.mode>=2)col.multiplyScalar(.65);c[i*3]=col.r;c[i*3+1]=col.g;c[i*3+2]=col.b;}
 setPreset(id){this.dispose();this.id=id;const kind=presets[id].kind;this.group.rotation.set(0,0,0);const amp=i=>this.bins[(Math.floor(i)%96+96)%96];
 if(['terrain','waterfall','contours'].includes(kind)){
  const rows=48,cols=80,v=this.lines(rows*(cols-1)*2);const hist=Array.from({length:rows},()=>new Float32Array(96));let last=-1;
  this.updateFn=t=>{if(Math.floor(t*24)!==last){hist.pop();hist.unshift(Float32Array.from(this.bins));last=Math.floor(t*24);}let k=0;for(let z=0;z<rows;z++)for(let x=0;x<cols-1;x++)for(let q=0;q<2;q++){const xx=x+q,frequency=Math.floor(xx/cols*96),a=kind==='waterfall'?hist[z][frequency]:amp(frequency);v.p[k*3]=(xx-cols/2)*.18;v.p[k*3+1]=(kind==='contours'?Math.sin(xx*.15+t+z*.18)*.22:Math.sin(xx*.1+t+z*.2)*.12)+a*(kind==='waterfall'?2.8:1.8)*Math.sin(z*.12+t*.6);v.p[k*3+2]=(z-rows/2)*.22;this.color(v.c,k++,xx/cols*.7,.35+z/rows*.65);}this.group.rotation.x=.55;this.group.rotation.y=Math.sin(t*.09)*.12;this.group.position.y=-.6;v.g.attributes.position.needsUpdate=true;v.g.attributes.color.needsUpdate=true;};
 }else if(['stars','sphere','pixels'].includes(kind)){
  const count=kind==='sphere'?7000:3500,v=this.lines(count,true),seeds=Array.from({length:count},(_,i)=>{const a=i*2.399963,r=Math.sqrt((i+.5)/count);return {a,r,x:Math.sin(i*17.13)*6,y:Math.cos(i*7.73)*4,z:(i/count)*20};});
  this.updateFn=t=>{for(let i=0;i<count;i++){const s=seeds[i],a=amp(i);if(kind==='sphere'){const y=1-2*(i+.5)/count,rr=Math.sqrt(1-y*y),radius=3.2+a*.8;v.p.set([Math.cos(s.a+t*.08)*rr*radius,y*radius,Math.sin(s.a+t*.08)*rr*radius],i*3);}else if(kind==='pixels'){v.p.set([s.x,s.y-((t*.6+i*.001)%8)+4,Math.sin(i)*3],i*3);}else{const z=(s.z+t*(1+this.level*4))%20-12;v.p.set([s.x*(.4+Math.abs(z)*.05),s.y*(.4+Math.abs(z)*.05),z],i*3);}this.color(v.c,i,i/count,.4+a*.6);}v.obj.material.size=kind==='pixels'?.085:.028+this.level*.03;this.group.position.y=0;v.g.attributes.position.needsUpdate=true;v.g.attributes.color.needsUpdate=true;};
 }else if(['globe','crystals','prisms','cubes'].includes(kind)){
  const count=kind==='globe'?3:kind==='cubes'?27:16,objects=[];for(let i=0;i<count;i++){const g=kind==='globe'?new THREE.DodecahedronGeometry(1.6,1):kind==='cubes'?new THREE.BoxGeometry(.7,.7,.7):new THREE.IcosahedronGeometry(.45+(i%3)*.12,0);const wire=new THREE.LineSegments(new THREE.EdgesGeometry(g),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.8}));g.dispose();this.group.add(wire);objects.push(wire);}
  this.updateFn=t=>{objects.forEach((o,i)=>{if(kind==='globe'){o.position.set((i-1)*3.4,Math.sin(t*.5+i)*.3,0);}else if(kind==='cubes'){o.position.set((i%3-1)*1.8,(Math.floor(i/3)%3-1)*1.8,(Math.floor(i/9)-1)*1.8);}else{o.position.set(Math.cos(i*2.4+t*.1)*(2+i%3),Math.sin(i*2.4+t*.12)*(1.5+i%3*.6),Math.sin(i*1.7)*2);}o.rotation.set(t*.15+i,t*.2+i*.4,t*.07);o.scale.setScalar(1+amp(i*5)*.6);o.material.color.set(this.mode%2===0?(this.mode>=2?0x333333:0xffffff):new THREE.Color().setHSL((i/count+t*.02)%1,.85,.6));});this.group.rotation.y=kind==='cubes'?t*.1:0;this.group.position.y=0;};
 }else if(kind==='network'){
  const n=120,v=this.lines(n*3*2),points=this.lines(n,true);this.updateFn=t=>{for(let i=0;i<n;i++){const a=i*2.39996,y=1-2*i/n,r=Math.sqrt(1-y*y)*(3+amp(i)*.8);points.p.set([Math.cos(a+t*.1)*r,y*3,Math.sin(a+t*.1)*r],i*3);this.color(points.c,i,i/n);}let k=0;for(let i=0;i<n;i++)for(const offset of [1,5,13])for(const j of [i,(i+offset)%n]){v.p.set(points.p.subarray(j*3,j*3+3),k*3);this.color(v.c,k++,i/n,.6);}for(const z of [points,v]){z.g.attributes.position.needsUpdate=true;z.g.attributes.color.needsUpdate=true;}this.group.rotation.z=Math.sin(t*.1)*.2;this.group.position.y=0;};
 }else if(kind==='hex'){
 const v=this.lines(17*11*6*2);this.updateFn=t=>{let k=0;for(let y=0;y<11;y++)for(let x=0;x<17;x++){const cx=(x-8)*.6,cy=(y-5)*.69+(x%2)*.345,r=.33+amp(x+y*4)*.1;for(let j=0;j<6;j++)for(let q=0;q<2;q++){const a=(j+q)*TAU/6;v.p.set([cx+Math.cos(a)*r,cy+Math.sin(a)*r,Math.sin(x*.4+y*.3+t)*this.level],k*3);this.color(v.c,k++,x/17);}}v.g.attributes.position.needsUpdate=true;v.g.attributes.color.needsUpdate=true;this.group.position.y=0;};
 }else{
  const paths=kind==='halos'?9:kind==='bars'?96:kind==='ribbons'||kind==='wave'?6:kind==='tunnel'?32:kind==='orbits'?12:kind==='satellite'?18:kind==='vortex'?24:kind==='liquid'?8:kind==='rings'?16:1;
  const segments=kind==='bars'?1:kind==='radial'?192:240,v=this.lines(paths*segments*2);
  this.updateFn=t=>{let k=0;for(let j=0;j<paths;j++)for(let i=0;i<segments;i++)for(let q=0;q<2;q++){const u=(i+q)/segments,a=u*TAU,f=amp(u*95+j*3);let x,y,z=0;
   if(kind==='bars'){x=(j-48)*.12;y=(q?amp(j)*4:0)-1.8;}
   else if(kind==='wave'||kind==='ribbons'){x=(u-.5)*12;y=Math.sin(u*TAU*(2+j*.4)+t*(.5+j*.1))*(.2+f*2)+(j-2.5)*.38;z=kind==='ribbons'?Math.cos(u*TAU+t+j)*.7:0;}
   else if(kind==='radial'){const radius=(q?2+f*3:1.8);x=Math.cos(i/segments*TAU)*radius;y=Math.sin(i/segments*TAU)*radius*.55;z=Math.sin(i/segments*TAU)*radius*.45;}
   else if(kind==='tunnel'){const r=1.5+((j/paths+t*.1)%1)*7;x=Math.cos(a+t*.12)*r;y=Math.sin(a+t*.12)*r;z=-((j/paths+t*.1)%1)*20+6;}
   else if(kind==='halos'){const r=.75+f*.35;x=(j%3-1)*3+Math.cos(a)*r;y=(Math.floor(j/3)-1)*2.3+Math.sin(a)*r;}
   else if(kind==='flower'){const r=2.2+.65*Math.sin(a*8+t)+f; x=Math.cos(a)*r;y=Math.sin(a)*r;z=Math.sin(a*4+t)*.8;}
   else {const r=kind==='satellite'?1+j*.16:kind==='liquid'?2.4+j*.07:kind==='vortex'?.5+j*.15:1.1+j*.16;const twist=kind==='vortex'?j*.19+t*.3:0;const deform=kind==='liquid'?Math.sin(a*3+t+j*.3)*(.4+this.level):f*.65;x=Math.cos(a+twist)*(r+deform);y=Math.sin(a+twist)*(r+deform)*(kind==='orbits'?.35:1);z=kind==='satellite'?Math.sin(a)*r*.6:Math.sin(a*3+t+j*.2)*this.level*.7;if(kind==='orbits'){y+=Math.sin(j)*.6;z=Math.sin(a+j)*r*.6;}}
   v.p.set([x,y,z],k*3);this.color(v.c,k++,u*.8+j/paths*.2,.45+.55*(1-j/paths));}
   this.group.rotation.x=kind==='rings'?.6:0;this.group.rotation.z=kind==='orbits'?t*.08:0;this.group.position.y=0;v.g.attributes.position.needsUpdate=true;v.g.attributes.color.needsUpdate=true;};
 }
 }
 render(t,bins,level){for(let i=0;i<96;i++)this.bins[i]+=(bins[i]-this.bins[i])*.22;this.level+=(level-this.level)*.18;this.scene.background=new THREE.Color(this.mode>=2?0xf2f1ef:0x000000);this.updateFn(t);for(const o of this.group.children){if(o.isPoints)o.material.blending=this.mode>=2?THREE.NormalBlending:THREE.AdditiveBlending;}this.bloom.enabled=this.mode<2;if(this.mode<2)this.composer.render();else this.renderer.render(this.scene,this.camera);}
 diagnostics(){const gl=this.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),webglError:gl.getError(),drawCalls:this.renderer.info.render.calls};}
 thumbnail(){const source=this.renderer.domElement;const c=document.createElement('canvas');c.width=480;c.height=280;const ctx=c.getContext('2d');const w=source.width*.82,h=w/1.714;ctx.drawImage(source,(source.width-w)/2,(source.height-h)/2,w,h,0,0,480,280);return c.toDataURL('image/png');}
}
